# Generated by Django 4.0.6 on 2022-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuts_name', models.CharField(max_length=100)),
                ('cuts_address', models.TextField()),
                ('cuts_ph', models.CharField(max_length=12)),
                ('gender', models.TextField()),
                ('id_proof_type', models.TextField()),
                ('id_proof_number', models.TextField()),
                ('cuts_image', models.ImageField(upload_to='customer_pic')),
                ('status', models.TextField()),
            ],
        ),
    ]
