# Generated by Django 4.0.6 on 2022-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='cuts_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
