# Generated by Django 4.0.6 on 2022-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_tb_cuts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='cuts_password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
