# Generated by Django 4.0.6 on 2022-08-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_tb_cuts_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_tb',
            old_name='cuts_email',
            new_name='email',
        ),
    ]
