# Generated by Django 4.0.6 on 2022-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cuts_email_customer_tb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('other', 'other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='id_proof_type',
            field=models.CharField(choices=[('adhar card', 'adhar card'), ('voter id', 'voter id'), ('licence', 'lience')], max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='customer_tb',
            table='Customer_tb',
        ),
    ]
